### ISSUE TITLE
ngx-konami module not found with v1.5.0

### ISSUE THREAD

**Issue by lmichondev** [lauthieb/ngx-konami#2]
Hi,

With the new release v1.5.0, doing this, as specified in the README.md

```javascript
import { KonamiModule } from 'ngx-konami';
```

no longer works and result in a `error TS2307: Cannot find module 'ngx-konami'`;

I had to do this to work because of the `dist/` folder that popped out

```javascript
import { KonamiModule } from 'ngx-konami/dist';
```

Is it intended or did you missed something in your publish process ?

**Comment by lauthieb** [comment]
Hi @lmichondev ! Thanks for your issue, I made a mistake in my publish process.
I've fixed that in v1.6.0.
Have a nice day ;)
