### ISSUE TITLE
Peer Dependency warning with Angular 6

### ISSUE THREAD

**Issue by tstackhouse** [lauthieb/ngx-konami#3]
When using this with Angular 6, yarn complains about depencency versions:

```
warning " > ngx-konami@1.6.0" has incorrect peer dependency "@angular/core@^4.0.0".
warning " > ngx-konami@1.6.0" has incorrect peer dependency "rxjs@^5.1.0".
```

Not sure if there are code implications, but changing the dependencies to something more like `"@angular/core": "4.0.0. | 5.0.0 | 6.0.0"` should make yarn happy, may also want to consider moving requirements such as angular to `peerDepencendies` instead of being in `devDependencies`.

**Comment by lauthieb** [comment]
Hello 1.7.0 with no warning 🎉 https://www.npmjs.com/package/ngx-konami
