### ISSUE TITLE
Ivy / Angular 9 compatibility

### ISSUE THREAD

**Issue by matcho** [lauthieb/ngx-konami#4]
Hi,

I just updated my Angular 8 app to v9, and I get the following error when building.
```
ERROR in node_modules/ngx-konami/index.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

export declare class KonamiModule {
                       ~~~~~~~~~~~~
```

From what I understood it's probably linked to the use of Ivy compiler by default with Angular 9, and the fact that it is not compatible with minified and/or compiled es5 code (not sure of that part).
See: https://github.com/angular/angular/issues/35255

Disabling Ivy in `tsconfig` does the trick so it's not such a big deal, but maybe it still could be made Ivy-compatible ?

Thanks

**Comment by bfaulk96** [comment]
Any maintainers available to look over @matcho's PR?

**Comment by lauthieb** [comment]
Thanks @matcho & @bfaulk96!

Hello 1.7.0 🎉 https://www.npmjs.com/package/ngx-konami
