### ISSUE TITLE
ERROR: 'ModuleWithProviders' is not generic. - Angular 9

### ISSUE THREAD

**Issue by jemd15** [lauthieb/ngx-konami#8]
Hi @lauthieb,

When I imported the library in the app.module.ts, I got this error

```
ERROR in C:/Users/x_jem/Documents/Projects/www/titanxELearning/node_modules/ngx-konami/index.d.ts (4,23): Type 'ModuleWithProviders' is not generic.

ERROR in Error: Metadata version mismatch for module C:/Users/x_jem/Documents/Projects/www/titanxELearning/node_modules/ngx-konami/ngx-konami.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/x_jem/Documents/Projects/www/titanxELearning/src/app/app.module.ts, resolving symbol AppModule in C:/Users/x_jem/Documents/Projects/www/titanxELearning/src/app/app.module.ts
```

Do you have an idea what can I do to solve this?

**Comment by lauthieb** [comment]
Hi, sorry I have no idea...
It works for me.
Do you have the same angular version for all of your packages?
I've just see this: https://stackoverflow.com/questions/51763710/angular-6-error-ts2315-type-modulewithproviders-is-not-generic

**Comment by lauthieb** [comment]
@matcho can you help us please?

**Comment by jemd15** [comment]
Sorry man, finally I got the solution. I'd been using an old version of the angular-cli, so when I updated it the error was gone. Thanks for the help :)
